version: '3.9'
name: Porperty Service
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: user
    #   POSTGRES_PASSWORD: password
    #   POSTGRES_DB: listings_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_cache
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data: