# Generated by Django 5.2.5 on 2025-08-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
    ]
